### ISSUE TITLE
bad config path in dockerfile

### ISSUE THREAD

**Issue by Ornias1993** [Supporterino/truenas-graphite-to-prometheus#11]
Copying things to /tmp inside a dockerfile is pretty bad practice, as a lot of systems/people/places replace the /tmp mountpoint with the actual ramdisk it represents.

/config would be a better endpoint

**Comment by Supporterino** [comment]
Thanks for pointing out. I threw it there during testing an never changed it. Will push a hot fix later to move it.

**Comment by Ornias1993** [comment]
> Thanks for pointing out. I threw it there during testing an never changed it. Will push a hot fix later to move it.

Found why you did so though, seems upstream also does this...
So a fairly honest mistake.

Also:
We've added (a variant of) this to the TrueCharts catalog as TrueNAS Exporter.

**Comment by Supporterino** [comment]
Changed in https://github.com/Supporterino/truenas-graphite-to-prometheus/releases/tag/v1.1.2

**Comment by Ornias1993** [comment]
cool!
