### ISSUE TITLE
An error has occurred while serving metrics:Dragonfish-24.04.0

### ISSUE THREAD

**Issue by mglants** [Supporterino/truenas-graphite-to-prometheus#27]
Running Dragonfish-24.04.0
An error has occurred while serving metrics:

668 error(s) occurred:
* collected metric "nfs_" { label:{name:"instance"  value:""}  label:{name:"job"  value:"truenas"}  label:{name:"op"  value:""}  gauge:{value:0.2}} was collected before with the same name and label values

**Comment by MGlants** [comment]
<img width="479" alt="image" src="https://github.com/Supporterino/truenas-graphite-to-prometheus/assets/35956828/f34ffc2a-2a88-4b5b-a339-16ee98f2cff5">

**Comment by Supporterino** [comment]
Hi there,

the namespace field seems to be new. I haven't updated to Dragonfish yet. Going to do that soon and give you feedback / update the docs or mappings. 

Greetings

**Comment by Supporterino** [comment]
Upgraded my secondary TrueNas box to Dragonfish and my metrics are working fine. @mglants where exactly do you get those error messages and how does your setup look like ?

**Comment by mglants** [comment]
prom/graphite-exporter:v0.15.1 running in kubernetes, config loaded directly, truenas is contaction it using direct IP conntection
i got this message, on access metrics page
setup is on screenshot above, how can i debug it?

**Comment by Supporterino** [comment]
That sounds pretty much like my setup I use internally. Could you make sure that the mappings are actually loaded by your graphite-exporter. And what metrics page you mean ? graphite-exporters metrics endpoint ? if so turn the log level up to debug in the exporter and check/share logs
